FROM ghcr.io/ggerganov/llama.cpp:server

ARG MODEL_URL=https://huggingface.co/Qwen/Qwen2.5-0.5B-Instruct-GGUF/resolve/main/qwen2.5-0.5b-instruct-q4_k_m.gguf
ARG MODEL_PATH=/app/models/model.gguf

# Передаем токен через аргумент сборки
ARG HF_TOKEN
ENV HF_TOKEN=${HF_TOKEN}

RUN mkdir -p /app/models && \
    # Используем curl с заголовком авторизации
    curl -L -H "Authorization: Bearer ${HF_TOKEN}" -o ${MODEL_PATH} ${MODEL_URL} && \
    ls -lh ${MODEL_PATH}

EXPOSE 8001

ENTRYPOINT ["./llama-server"]
CMD ["--model", "/app/models/model.gguf", "--host", "0.0.0.0", "--port", "8001", "--ctx-size", "4096", "--n-predict", "256", "--threads", "4"]